# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-23 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='Image_Description',
            field=models.TextField(null=True),
        ),
    ]
